language: csharp
mono: none
os: linux
dist: xenial
dotnet: 3.1.403

addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: latest/stable

script:
  - dotnet restore
  - dotnet test -f netcoreapp2.1

