version: 1.0.5.{build}
skip_tags: true
nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build_script:
  - ps: >-
      dotnet build YaWhois --configuration Release --no-restore --framework netstandard2.0

test_script:
  - ps: >-
      OpenCover.Console.exe -register:appveyor -filter:"+[YaWhois]*" -target:"dotnet.exe" -targetargs:"test YaWhois.Tests --no-restore --verbosity minimal --framework netcoreapp3.1" -output:coverage.xml

after_test:
  - codecov -f "coverage.xml"

