//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaWhois.Tests.WhoisClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrsNic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrsNic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaWhois.Tests.WhoisClient.Resources.CrsNic", typeof(CrsNic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Domain Name: MAIL.COM
        ///   Registry Domain ID: 3083119_DOMAIN_COM-VRSN
        ///   Registrar WHOIS Server: whois.psi-usa.info
        ///   Registrar URL: http://www.psi-usa.info
        ///   Updated Date: 2020-03-26T07:05:03Z
        ///   Creation Date: 1997-03-24T05:00:00Z
        ///   Registry Expiry Date: 2021-03-25T04:00:00Z
        ///   Registrar: PSI-USA, Inc. dba Domain Robot
        ///   Registrar IANA ID: 151
        ///   Registrar Abuse Contact Email: domain-abuse@psi-usa.info
        ///   Registrar Abuse Contact Phone: +49.94159559482
        ///   Domain Status: clientTransferProhi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mail_com {
            get {
                return ResourceManager.GetString("mail.com", resourceCulture);
            }
        }
    }
}
