//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaWhois.Tests.WhoisClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RIPE_NotFiltered {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RIPE_NotFiltered() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaWhois.Tests.WhoisClient.Resources.RIPE_NotFiltered", typeof(RIPE_NotFiltered).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % This is the RIPE Database query service.
        ///% The objects are in RPSL format.
        ///%
        ///% The RIPE Database is subject to Terms and Conditions.
        ///% See http://www.ripe.net/db/support/db-terms-conditions.pdf
        ///
        ///% Information related to &apos;80.80.80.0 - 80.80.81.255&apos;
        ///
        ///% Abuse contact for &apos;80.80.80.0 - 80.80.81.255&apos; is &apos;abuse@freenom.com&apos;
        ///
        ///inetnum:        80.80.80.0 - 80.80.81.255
        ///netname:        NL-OPENTLD-20050330
        ///descr:          Freenom DNS Cloud IP Space
        ///descr:          Abuse: please contact abuse@freenom.com [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _B_80_80_80_80 {
            get {
                return ResourceManager.GetString("-B 80.80.80.80", resourceCulture);
            }
        }
    }
}
